/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model2({ ...props }) {
  const group = useRef()
  useFrame(() => {
    // AllRef.current.rotation.x += 0.03;
    group.current.rotation.y += 0.005;
  });
  const { nodes, materials } = useGLTF('/contactShip.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cylinder006_Material001_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cylinder006_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder006_Material002_0001.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder006_Material003_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cylinder006_Material004_0.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Cylinder006_Material005_0.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Cylinder006_Material_0.geometry} material={materials['Material.007']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/contactShip.gltf')
