/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.003']} position={[0, 1, 0]} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.002']} position={[0, 1, 0]} scale={1.04} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[0.52, 1.86, 0.36]} rotation={[0.37, -0.1, -0.52]} scale={-0.02} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[0.65, 1.86, -0.1]} rotation={[-0.07, 0.06, -0.7]} scale={-0.02} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.004']} position={[0.72, 1.81, 0.04]} rotation={[0.04, -0.1, -0.7]} scale={-0.02} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.004']} position={[0.58, 1.89, 0.17]} rotation={[0.11, -0.16, -0.55]} scale={-0.02} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.004']} position={[0.5, 1.96, 0.01]} rotation={[0.04, -0.16, -0.41]} scale={-0.02} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[0.6, 1.69, 0.57]} rotation={[0.54, -0.34, -0.63]} scale={-0.01} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.004']} position={[1, 1.18, 0.37]} rotation={[0.46, -0.21, -1.28]} scale={-0.02} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.004']} position={[0.71, 1.68, 0.45]} rotation={[0.4, -0.22, -0.66]} scale={-0.02} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.004']} position={[1.05, 1.07, 0.26]} rotation={[0.41, -0.11, -1.43]} scale={-0.02} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['Material.004']} position={[0.51, 1.6, 0.74]} rotation={[0.64, -0.38, -0.44]} scale={-0.02} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.004']} position={[0.28, 1.77, 0.71]} rotation={[0.55, -0.35, -0.31]} scale={-0.02} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.004']} position={[0.3, 1.9, 0.5]} rotation={[0.37, -0.29, -0.36]} scale={-0.02} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.004']} position={[0.63, 1.57, 0.67]} rotation={[0.52, -0.36, -0.63]} scale={-0.01} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.004']} position={[0.6, 1.37, 0.82]} rotation={[0.76, -0.53, -0.67]} scale={-0.02} />
      <mesh geometry={nodes.Plane018.geometry} material={materials['Material.004']} position={[0.79, 1.31, 0.67]} rotation={[0.56, -0.34, -0.93]} scale={-0.01} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.004']} position={[0.64, 1.15, 0.85]} rotation={[0.83, -0.62, -0.79]} scale={-0.02} />
      <mesh geometry={nodes.Plane020.geometry} material={materials['Material.004']} position={[0.75, 1.16, 0.76]} rotation={[0.77, -0.56, -0.98]} scale={-0.01} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Material.004']} position={[0.97, 1.02, 0.47]} rotation={[0.64, -0.33, -1.22]} scale={-0.01} />
      <mesh geometry={nodes.Plane022.geometry} material={materials['Material.004']} position={[1.01, 0.82, 0.31]} rotation={[0.64, -0.36, -1.53]} scale={-0.02} />
      <mesh geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} position={[0.68, 0.87, -0.83]} rotation={[0.94, 0.51, -2.41]} scale={-0.02} />
      <mesh geometry={nodes.Plane024.geometry} material={materials['Material.004']} position={[-0.42, 1.5, 0.86]} rotation={[1.38, -0.59, 0.52]} scale={-0.02} />
      <mesh geometry={nodes.Plane025.geometry} material={materials['Material.004']} position={[-0.49, 1.72, 0.64]} rotation={[1.23, -0.68, 0.71]} scale={-0.02} />
      <mesh geometry={nodes.Plane026.geometry} material={materials['Material.004']} position={[-0.61, 1.44, 0.77]} rotation={[1.5, -0.48, 0.69]} scale={-0.02} />
      <mesh geometry={nodes.Plane028.geometry} material={materials['Material.004']} position={[-0.7, 1.57, 0.59]} rotation={[1.36, -0.6, 0.84]} scale={-0.02} />
      <mesh geometry={nodes.Plane029.geometry} material={materials['Material.004']} position={[-0.65, 1.21, -0.91]} rotation={[1.35, -0.53, 2.41]} scale={-0.01} />
      <mesh geometry={nodes.Plane030.geometry} material={materials['Material.004']} position={[-0.8, 1.13, -0.8]} rotation={[1.23, -0.42, 2.26]} scale={-0.02} />
      <mesh geometry={nodes.Plane031.geometry} material={materials['Material.004']} position={[-0.74, 0.98, -0.87]} rotation={[1.12, -0.3, 2.32]} scale={-0.02} />
      <mesh geometry={nodes.Plane032.geometry} material={materials['Material.004']} position={[-0.49, 1.06, -1.03]} rotation={[1.39, -0.5, 2.6]} scale={-0.02} />
      <mesh geometry={nodes.Plane033.geometry} material={materials['Material.004']} position={[-0.5, 0.83, -1.01]} rotation={[1.25, -0.43, 2.62]} scale={-0.02} />
      <mesh geometry={nodes.Plane034.geometry} material={materials['Material.004']} position={[-0.56, 0.65, -0.85]} rotation={[0.52, -0.74, 2.32]} scale={-0.02} />
      <mesh geometry={nodes.Plane035.geometry} material={materials['Material.004']} position={[-0.16, 1.08, -1.06]} rotation={[1.46, -0.91, 2.88]} scale={-0.02} />
      <mesh geometry={nodes.Plane036.geometry} material={materials['Material.004']} position={[0.55, 1.22, -0.91]} rotation={[2.3, -0.61, -2.36]} scale={-0.01} />
      <mesh geometry={nodes.Plane037.geometry} material={materials['Material.004']} position={[0.34, 0.65, -0.96]} rotation={[1.65, -0.98, -2.6]} scale={-0.01} />
      <mesh geometry={nodes.Plane038.geometry} material={materials['Material.004']} position={[0.36, 0.51, -0.89]} rotation={[1.76, -0.95, -2.35]} scale={-0.01} />
      <mesh geometry={nodes.Plane039.geometry} material={materials['Material.004']} position={[0.75, 1.1, -0.76]} rotation={[2.23, -0.47, -2.23]} scale={-0.02} />
      <mesh geometry={nodes.Plane040.geometry} material={materials['Material.004']} position={[0.79, 0.89, -0.72]} rotation={[2.15, -0.57, -2.15]} scale={-0.02} />
      <mesh geometry={nodes.Plane041.geometry} material={materials['Material.004']} position={[0.5, 0.79, -0.93]} rotation={[1.92, -0.71, -2.5]} scale={-0.02} />
      <mesh geometry={nodes.Plane042.geometry} material={materials['Material.004']} position={[0.83, 0.72, -0.63]} rotation={[2.03, -0.59, -1.95]} scale={-0.01} />
      <mesh geometry={nodes.Plane043.geometry} material={materials['Material.004']} position={[0.7, 0.61, -0.72]} rotation={[0.71, 0.35, -2.39]} scale={-0.02} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.004']} position={[-0.64, 0.67, 0.8]} rotation={[2.1, -0.16, 0.58]} scale={-0.02} />
      <mesh geometry={nodes.Plane044.geometry} material={materials['Material.004']} position={[-0.4, 0.54, 0.89]} rotation={[2.1, -0.16, 0.44]} scale={-0.02} />
      <mesh geometry={nodes.Plane046.geometry} material={materials['Material.004']} position={[-0.62, 0.39, 0.63]} rotation={[2.36, 0.01, 0.58]} scale={-0.02} />
      <mesh geometry={nodes.Plane047.geometry} material={materials['Material.004']} position={[-0.12, 0.34, 0.93]} rotation={[2.27, -0.02, 0.07]} scale={-0.02} />
      <mesh geometry={nodes.Plane048.geometry} material={materials['Material.004']} position={[-0.29, 0.23, 0.8]} rotation={[2.48, 0.02, 0.29]} scale={-0.02} />
      <mesh geometry={nodes.Plane049.geometry} material={materials['Material.004']} position={[-0.01, 0.22, 0.84]} rotation={[2.27, -0.02, 0.07]} scale={-0.02} />
      <mesh geometry={nodes.Plane050.geometry} material={materials['Material.004']} position={[-0.28, 0.1, 0.65]} rotation={[2.48, 0.02, 0.29]} scale={-0.02} />
      <mesh geometry={nodes.Plane045.geometry} material={materials['Material.004']} position={[0.43, 1.05, -0.99]} rotation={[2.13, -0.73, -2.49]} scale={-0.01} />
      <group position={[0.72, 1.42, 0.69]} rotation={[0.72, -0.3, -0.72]} scale={0.41}>
        <mesh geometry={nodes.Plane056.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane056_1.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Plane079.geometry} material={nodes.Plane079.material} position={[-0.81, 0.38, -0.17]} rotation={[1.37, 0.66, 1.87]} scale={0.01} />
      <mesh geometry={nodes.Plane081.geometry} material={nodes.Plane081.material} position={[-0.04, 0.7, -0.99]} rotation={[1.25, 1.12, 3.1]} scale={0.02} />
      <group position={[0.44, 0.43, 0.74]} rotation={[0.5, -1.17, -1.75]} scale={0.03}>
        <mesh geometry={nodes.Plane090_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Plane090_2.geometry} material={materials.WHITE} />
      </group>
      <group position={[-0.89, 0.61, -0.33]} rotation={[-0.2, -0.36, 1.86]} scale={0.2}>
        <mesh geometry={nodes.Plane092.geometry} material={materials.WINDOW} />
        <mesh geometry={nodes.Plane092_1.geometry} material={materials['Material.010']} />
      </group>

    </group>
  )
}

useGLTF.preload('/earth.gltf')
