/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model5({xMov=0, yMov=0, xRot=0, ...props }) {
  const group = useRef()
  useFrame(() => {
    group.current.position.x -= xMov 
    group.current.rotation.x += xRot
    group.current.position.y += yMov
  });
  const { nodes, materials } = useGLTF('/webappShip.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-5.54, -1.2, 0.1]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[206.45, 38.41, 7.74]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
            <group position={[-45.86, -2.21, 27.85]} rotation={[-Math.PI / 2, 0, -2.44]} scale={0.25}>
              <mesh geometry={nodes['272727_161_0'].geometry} material={materials.material_12} />
            </group>
            <group position={[65.68, 0.02, 15.94]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.64, 0.35, 0.56]}>
              <mesh geometry={nodes['Box00335687_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[38.7, -13.62, 16.87]} rotation={[-1.75, 0.07, -0.02]} scale={[-0.25, -0.17, -0.2]}>
              <mesh geometry={nodes['Box0043568_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[38.7, 13.42, 16.87]} rotation={[-1.39, -0.07, 3.12]} scale={[0.25, 0.17, 0.2]}>
              <mesh geometry={nodes['Box0053568_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[38.7, -19.11, -16.75]} rotation={[1.76, -0.04, -2.99]} scale={[0.25, 0.17, 0.2]}>
              <mesh geometry={nodes['Box0062727_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[38.7, 21.69, -16.75]} rotation={[1.38, 0.04, 0.15]} scale={[-0.25, -0.17, -0.2]}>
              <mesh geometry={nodes['Box007274_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-13.3, 7.24, -37.82]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.11, 0.96, 0.28]}>
              <mesh geometry={nodes.Box335689_fghfghjgh_0.geometry} material={materials.fghfghjgh} />
            </group>
            <group position={[-13.3, -7.24, -37.82]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.11, -0.96, -0.28]}>
              <mesh geometry={nodes.Box335690_fghfghjgh_0.geometry} material={materials.fghfghjgh} />
            </group>
            <group position={[71.87, -5.93, 30.94]} rotation={[0, 1.48, -1.75]} scale={[-0.49, -0.49, -0.71]}>
              <mesh geometry={nodes['Cha3456mferCyl018_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[71.87, 5.62, 30.94]} rotation={[Math.PI, -1.48, 1.75]} scale={[0.49, 0.49, 0.71]}>
              <mesh geometry={nodes['Chamf3456erCyl019_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-1.68, -62.08, -4.49]} rotation={[-1.75, -Math.PI / 2, 0]} scale={[0.49, 0.49, 0.51]}>
              <mesh geometry={nodes['ChamferC27yl022_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-1.68, 61.9, -4.49]} rotation={[-1.75, -Math.PI / 2, 0]} scale={[0.49, 0.49, 0.51]}>
              <mesh geometry={nodes['ChamferCyl02427_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-48.04, -2.22, 25]} rotation={[Math.PI, Math.PI / 4, -Math.PI / 2]} scale={0.25}>
              <group position={[0, -2.76, -5.92]} rotation={[-0.44, 0, 0]}>
                <mesh geometry={nodes.ChamferCyl025_161_0.geometry} material={materials.material_12} />
              </group>
            </group>
            <group position={[-45.91, 2.13, 27.93]} rotation={[-Math.PI, 0.17, -Math.PI / 2]} scale={0.25}>
              <group position={[0, -2.76, -5.92]} rotation={[-0.44, 0, 0]}>
                <mesh geometry={nodes['ChamferCyl026_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
              </group>
            </group>
            <group position={[-45.91, -2.22, 27.93]} rotation={[-Math.PI, 0.17, -Math.PI / 2]} scale={0.25}>
              <group position={[0, -2.76, -5.92]} rotation={[-0.44, 0, 0]}>
                <mesh geometry={nodes.ChamferCyl027_161_0.geometry} material={materials.material_12} />
              </group>
            </group>
            <group position={[-48.04, 2.13, 25]} rotation={[Math.PI, Math.PI / 4, -Math.PI / 2]} scale={0.25}>
              <group position={[0, -2.76, -5.92]} rotation={[-0.44, 0, 0]}>
                <mesh geometry={nodes.ChamferCyl02720_161_0.geometry} material={materials.material_12} />
              </group>
            </group>
            <group position={[52.25, -48.69, -9.31]} rotation={[0, 1.56, -1.75]} scale={[-0.49, -0.49, -0.93]}>
              <mesh geometry={nodes['ChamferCyl028_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[52.25, -38.76, -9.31]} rotation={[0, 1.56, -1.75]} scale={[-0.49, -0.49, -0.93]}>
              <mesh geometry={nodes['ChamferCyl029_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[52.25, 49.1, -9.31]} rotation={[0, 1.56, -1.75]} scale={[-0.49, -0.49, -0.93]}>
              <mesh geometry={nodes['ChamferCyl030_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[52.25, 39.17, -9.31]} rotation={[0, 1.56, -1.75]} scale={[-0.49, -0.49, -0.93]}>
              <mesh geometry={nodes['ChamferCyl031_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-1.68, -62.08, -12.2]} rotation={[-1.75, Math.PI / 2, 0]} scale={[-0.49, -0.49, -0.51]}>
              <mesh geometry={nodes['ChamferCyl0356817_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-1.68, 61.9, -12.2]} rotation={[-1.75, -Math.PI / 2, 0]} scale={[0.49, 0.49, 0.51]}>
              <mesh geometry={nodes['ChamferCyl27021_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[29.44, -14.55, 17.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes['Cylind56345er004_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[48.88, -14.55, 17.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes['Cylinder0013567_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[42.4, -14.55, 17.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes['Cylinder00237_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[35.92, -14.55, 17.44]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes['Cylinder003673_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-69.48, 9.76, -9.27]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-0.49}>
              <mesh geometry={nodes.Sph345634ere004_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[-49.95, 2.14, 25.72]} rotation={[Math.PI, 1.22, -Math.PI / 2]} scale={0.25}>
              <mesh geometry={nodes['Sphere005675_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-47.96, 2.14, 24.96]} rotation={[-Math.PI / 2, 0, -3.05]} scale={0.25}>
              <mesh geometry={nodes['Sphere0065687_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
            </group>
            <group position={[-47.96, -2.21, 24.96]} rotation={[-Math.PI / 2, 0, -3.05]} scale={0.25}>
              <mesh geometry={nodes.Sphere00727_161_0.geometry} material={materials.material_12} />
            </group>
            <group position={[-49.95, -2.21, 25.72]} rotation={[Math.PI, 1.22, -Math.PI / 2]} scale={0.25}>
              <mesh geometry={nodes['Sphere00827_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-45.86, 2.14, 27.85]} rotation={[-Math.PI / 2, 0, -2.44]} scale={0.25}>
              <mesh geometry={nodes['Sphere00927_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
            </group>
            <group position={[-47.06, -2.21, 29.61]} rotation={[Math.PI, 0.61, -Math.PI / 2]} scale={0.25}>
              <mesh geometry={nodes['Sphere011_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-47.06, 2.14, 29.61]} rotation={[Math.PI, 0.61, -Math.PI / 2]} scale={0.25}>
              <mesh geometry={nodes['Sphere012_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[69.92, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere013_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[64.36, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere014_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[58.8, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere015_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[53.25, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere016_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[47.69, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere017_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[42.13, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere018_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[36.57, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere019_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[31.01, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere020_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[25.45, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere021_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[19.89, -22.24, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere022_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[69.92, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere023_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[64.36, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere024_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[58.8, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere025_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[53.25, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere026_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[47.69, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere027_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[42.13, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere028_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[36.57, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere029_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[31.01, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere030_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[25.45, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere031_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[19.89, 22.56, 0.94]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.65}>
              <mesh geometry={nodes['Sphere032_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-69.48, -7.4, -9.27]} rotation={[Math.PI / 2, 0, 0]} scale={0.49}>
              <mesh geometry={nodes.Sphere0467803_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[-69.44, 10.14, -9.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes.Torus001_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[-69.44, -7.88, -9.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes.Torus002_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[-69.44, 2.27, -9.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes.Torus003_16161_0.geometry} material={materials['16161']} />
            </group>
            <group position={[-69.44, -1.43, -9.19]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes.Torus004_16161_0.geometry} material={materials['16161']} />
            </group>
            <group position={[-68.8, 0.03, -9.32]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.49, 0.49, 0.91]}>
              <mesh geometry={nodes.Torus005_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
              <mesh geometry={nodes.Torus005_body_color_2_0.geometry} material={materials.body_color_2} />
            </group>
            <group position={[-69.33, 1.01, -9.15]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.49, 0.49, 0.89]}>
              <mesh geometry={nodes['Torus006_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-81.59, 13.47, -7.73]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.63}>
              <mesh geometry={nodes['Tube005_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-89.04, 13.47, -7.73]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.63}>
              <mesh geometry={nodes['Tube006_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-96.32, 13.47, -7.73]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.63}>
              <mesh geometry={nodes['Tube007_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-74.53, 13.47, -7.73]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.63}>
              <mesh geometry={nodes['Tube008_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-74.53, -11.39, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube009_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-81.59, -11.39, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube010_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-89.04, -11.39, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube011_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-96.32, -11.39, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube012_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-81.59, -11.39, -7.73]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube013_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-89.04, -11.39, -7.73]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube014_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-96.32, -11.39, -7.73]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube015_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-74.53, -11.39, -7.73]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube016_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-69.25, -7.88, -9.18]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.49}>
              <mesh geometry={nodes.Tube018_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[-69.25, 7.93, -9.18]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.49}>
              <mesh geometry={nodes.Tube019_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[11.36, 30.98, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube024_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[3.9, 30.98, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube025_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-3.38, 30.98, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube026_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[18.41, 30.98, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube027_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[11.36, -29.43, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube028_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[3.9, -29.43, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube029_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-3.38, -29.43, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube030_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[18.41, -29.43, -5.01]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube031_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-74.53, 13.48, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube032_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-81.59, 13.48, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube033_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-89.04, 13.48, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube034_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-96.32, 13.48, -10.92]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.63}>
              <mesh geometry={nodes['Tube035_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/webappShip.gltf')
