/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model4({xMov=0, yMov=0, xRot=0, ...props }) {
  const group = useRef()
  useFrame(() => {
    group.current.position.x -= xMov 
    group.current.rotation.x += xRot
  });
  const { nodes, materials } = useGLTF('/webpageShip.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.03}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[0.85, 0.98, 0.82]}>
            <group position={[37.91, 0.39, -27.43]}>
              <mesh geometry={nodes['Box001_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
              <mesh geometry={nodes.Box001_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[-13.45, 4.79, -0.94]} rotation={[Math.PI / 2, 0, 0]} scale={[1.33, 1.18, 0.58]}>
              <mesh geometry={nodes.Box002_body_color_2_0.geometry} material={materials.body_color_2} />
            </group>
            <group position={[37.99, 14.56, -17.66]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.67, -1, -0.59]}>
              <mesh geometry={nodes.Box004_black_mat_for_body_0001.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[37.99, -14.56, -17.66]} rotation={[Math.PI / 2, 0, 0]} scale={[0.67, 1, 0.59]}>
              <mesh geometry={nodes.Box005_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[31, 0.45, 15.6]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['ChamferCyl001_07_-_Default_0001'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[53.53, 0.45, 27.04]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-0.65, -0.5, -0.5]}>
              <mesh geometry={nodes['ChamferCyl002_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[64.61, -30.34, -0.05]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['ChamferCyl003_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[64.61, 31.11, -0.05]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={-1}>
              <mesh geometry={nodes['ChamferCyl004_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[2, 14.92, -4.54]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[-0.26, -0.45, -0.45]}>
              <mesh geometry={nodes['ChamferCyl005_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[2, -14.11, -4.54]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.26, 0.45, 0.45]}>
              <mesh geometry={nodes['ChamferCyl006_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-64.01, 25.81, -20.09]} rotation={[-Math.PI / 2, 1.57, 0]} scale={-0.53}>
              <mesh geometry={nodes['ChamferCyl007_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-64.01, -24.98, -20.09]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.53}>
              <mesh geometry={nodes['ChamferCyl008_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-96.34, -14.59, -20.22]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['ChamferCyl009_07_-_Default_0001'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-96.34, 15.47, -20.22]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh geometry={nodes['ChamferCyl010_07_-_Default_0001'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[90.45, 0.45, 9.02]} rotation={[-Math.PI / 2, -1.57, 0]} scale={[-0.65, -0.5, -0.82]}>
              <mesh geometry={nodes['ChamferCyl011_07_-_Default_0001'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-84.11, 0.45, -15.7]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.71, 1]}>
              <mesh geometry={nodes['ChamferCyl012_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[106.69, -41.4, -17.68]} rotation={[-Math.PI, -1.57, 0]} scale={[1, 1, 0.36]}>
              <mesh geometry={nodes['Cylinder002_07_-_Default_0001'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[63.83, 49.52, -20]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-1, -0.59, -0.68]}>
              <mesh geometry={nodes['Cylinder003_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[106.69, 42.17, -17.68]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-1, -1, -0.36]}>
              <mesh geometry={nodes['Cylinder004_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[-36.52, 0.36, -13.8]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[3.98, 1, 1]}>
              <mesh geometry={nodes.Cylinder005_body_color_2_0.geometry} material={materials.body_color_2} />
            </group>
            <group position={[-36.85, -7.19, -20.17]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.48, 1, 1]}>
              <mesh geometry={nodes.Cylinder006_body_color_2_0.geometry} material={materials.body_color_2} />
            </group>
            <group position={[-36.85, 7.86, -20.17]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[-1.48, -1, -1]}>
              <mesh geometry={nodes.Cylinder007_body_color_2_0.geometry} material={materials.body_color_2} />
            </group>
            <group position={[116.89, -17.12, 9.26]} rotation={[0, -1.49, Math.PI]} scale={[0.22, 0.22, 0.14]}>
              <mesh geometry={nodes['Cylinder008_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[116.89, 17.94, 9.26]} rotation={[-Math.PI, 1.49, 0]} scale={[-0.22, -0.22, -0.14]}>
              <mesh geometry={nodes['Cylinder009_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[63.83, -49.52, -20]} rotation={[-Math.PI, -1.57, 0]} scale={[1, 0.59, 0.68]}>
              <mesh geometry={nodes['Cylinder010_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
            </group>
            <group position={[37.91, 22.34, -13.99]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[-0.45, -0.47, -1.08]}>
              <mesh geometry={nodes.Sphere003_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[52.86, 22.34, -14.72]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[-0.45, -0.47, -1.08]}>
              <mesh geometry={nodes.Sphere004_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[37.91, -22.34, -13.99]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.45, 0.47, 1.08]}>
              <mesh geometry={nodes.Sphere005_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
            <group position={[52.86, -22.34, -14.72]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.45, 0.47, 1.08]}>
              <mesh geometry={nodes.Sphere006_black_mat_for_body_0.geometry} material={materials.black_mat_for_body} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/webpageShip.gltf')
